version: "3.8"
services:
  storage:
    image: oittaa/gcp-storage-emulator
    env_file: ./.env.local
    environment:
      PORT: 9023
    ports:
      - "9023:9023"
    volumes:
      - ./.data/storage/:/storage
