services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123" # HTTP interface
      - "9000:9000" # Native client port
      - "9009:9009" # TCP for interserver communication (optional)
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    env_file:
      - ./env.local
    networks:
      - clickhouse-network
  bytebase:
    image: bytebase/bytebase:latest
    container_name: bytebase
    ports:
      - "8080:8080" # Bytebase UI port
    environment:
      - BYTEBASE_SERVER_PORT=8080
      - BYTEBASE_ADMIN_EMAIL=admin@admin.com
      - BYTEBASE_ADMIN_PASSWORD=admin
    depends_on:
      - clickhouse
    networks:
      - clickhouse-network

volumes:
  clickhouse_data:

networks:
  clickhouse-network:
    driver: bridge
    name: clickhouse-network
