services:
  postgres:
    image: postgres:17
    container_name: webhooks_postgres
    environment:
      POSTGRES_DB: webhooks
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./.db:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d webhooks"]
      interval: 10s
      timeout: 5s
      retries: 5
