version: "3.8"

services:

    postgres:
        image: postgres
        restart: always
        env_file:
            - '.env.local'
        volumes:
            - './.data/postgres:/var/lib/postgresql/data'

#    localstack:
#        container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
#        image: localstack/localstack
#        network_mode: bridge
#        ports:
#            - "127.0.0.1:53:53"
#            - "127.0.0.1:53:53/udp"
#            - "127.0.0.1:443:443"
#            - "127.0.0.1:4566:4566"
#            - "127.0.0.1:4571:4571"
#        environment:
#            - SERVICES=s3,dynamodb,kinesis
#            - DEBUG=1
#            - DATA_DIR=/tmp/localstack/data
#            - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
#            - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY- }
#            - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
#            - DOCKER_HOST=unix:///var/run/docker.sock
#            - HOST_TMP_FOLDER=${TMPDIR}
#        volumes:
#            - './.localstack:/tmp/localstack'
#            - "/var/run/docker.sock:/var/run/docker.sock"

#    mongodb:
#        image : mongo
#        container_name: mongodb
#        environment:
#            - PUID=1000
#            - PGID=1000
#        volumes:
#            - './.mongo:/data/db'
#            - './backup:/data/backups'
#        ports:
#            - 27017:27017
#        restart: unless-stopped

#    nats:
#        image: 'nats-streaming'
#        command:
#            - "--cluster"
#            - "nats://0.0.0.0:6222"
#            - "--cluster_id"
#            - nats-streaming
#            - "--clustered"
#            - "--cluster_bootstrap"
#            - "--cluster_log_path"
#            - /data/log
#            - "--cluster_node_id"
#            - nats-streaming-1
#            - "--cluster_raft_logging"
#            - "--debug"
#            - "--dir"
#            - /data/msg
#            - "--http_port"
#            - "8222"
#            - "--port"
#            - "4222"
#            - "--store"
#            - file
#            - "--stan_debug"
#            - "--hb_interval"
#            - 2s
#            - "--hb_fail_count"
#            - "1"
#            - "--hb_timeout"
#            - 5s
#        ports:
#            - "14222:4222"
#            - "18222:8222"
