version: "3.8"

# https://github.com/vegasbrianc/prometheus/blob/master/docker-compose.yml

volumes:
  prometheus_data: {}
  alertmanager_data: {}
  grafana_data: {}

networks:
#  otel-front-tier:
  otel-back-tier:

services:

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ../prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
#    links:
#      - alertmanager:alertmanager
    #      - pushgateway:pushgateway
#    depends_on:
    #      - pushgateway
    networks:
      - otel-back-tier
    restart: always

  grafana:
    image: grafana/grafana-enterprise
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - otel-back-tier

  infra-go-app:
    build:
      context: ..
    env_file: ../.env.local
    ports:
      - "9000:9000"
    restart: always
#    volumes:
#      - "./:/build/infra/"
    networks:
      - otel-back-tier
