{
 "title": "Backend Worker",
 "tags": [
  "golang",
  "metrics"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(image_processing_duration_sum{}[1m])) by (type) / sum(rate(image_processing_duration_count{}[1m])) by (type)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Application Error Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Error Count (5m)",
   "type": "timeseries",
   "description": "Total number of errors per service",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(error_total[1m])) by (job)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Processed Count (1m)",
   "type": "timeseries",
   "description": "Total number of errors per service",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(processed_images_total[1m])) by (job)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "description": "CPU usage per Go application",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"backend_worker\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "stat",
   "description": "Number of goroutines currently running",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"backend_worker\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Memory Usage (MB)",
   "type": "timeseries",
   "description": "Memory usage per Go application",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"backend_worker\"} / 1024 / 1024",
     "legendFormat": "{{instance}} - Allocated"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "timeseries",
   "description": "Garbage Collection statistics",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_count{job=\"backend_worker\"}[1m])",
     "legendFormat": "{{instance}} - GC runs/sec"
    },
    {
     "expr": "rate(go_gc_duration_seconds_sum{job=\"golang\"}[1m]) * 1000",
     "legendFormat": "{{instance}} - GC Pause Time"
    }
   ]
  }
 ]
}