global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration (optional, not configured in this setup)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# Scrape configurations
scrape_configs:
  # Scrape Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Scrape the NestJS metrics exporter
  - job_name: "nestjs-system-metrics"
    scrape_interval: 15s
    static_configs:
      - targets: ["nestjs-metrics:3000"] # Using Docker service name
    metrics_path: /metrics
