version: "3.8"

services:
  postgres:
    image: postgres:17-alpine
    restart: always
    env_file:
      - ".env.local"
    ports:
      - "5432:5432"
    command: "-c log_statement=all"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - faceblur-net

  storage:
    image: fsouza/fake-gcs-server
    ports:
      - "9023:8000"
    command: ["-scheme", "both", "-public-host", "localhost"]
    volumes:
      - ./.data/storage/:/storage
    networks:
      - faceblur-net

  rabbitmq:
    image: rabbitmq:4.0.7-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ main port
      - "15672:15672" # Management web interface port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - faceblur-net

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./infra/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - 9090:9090
    networks:
      - faceblur-net
    restart: always

  grafana:
    image: grafana/grafana-enterprise
    restart: unless-stopped
    ports:
      - "4000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - faceblur-net

volumes:
  postgres-data:
  rabbitmq_data:
  prometheus_data:
  grafana_data:

networks:
  faceblur-net:
