version: "3.8"

services:

    postgres:
        image: postgres
        restart: always
        env_file:
            - '.env.local'
        ports:
            - "5432:5432"
        command: "-c log_statement=all"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - faceblur-net

    storage:
        image: fsouza/fake-gcs-server
        ports:
            - "9023:8000"
        command: ["-scheme", "both", "-public-host", "localhost"]
        volumes:
            - ./.data/storage/:/storage
        networks:
            - faceblur-net

volumes:
    postgres-data:

networks:
    faceblur-net:
