openapi: 3.0.3
info:
  title: Workflows API
  description: A simple REST API for managing workflows
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:8080
    description: Development server
  - url: https://api.example.com
    description: Production server

paths:
  /v1/workflows/github:
    post:
      summary: Manage a GitHub workflow
      description: Manages a GitHub workflow to be executed
      operationId: manageGithubWorkflow
      tags:
        - Workflows
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GithubWorkflowRequest"
      responses:
        "200":
          description: Operation completed successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GithubWorkflowResponse"
              example:
                data:
                  message: "Workflow managed successfully"
        "400":
          description: Bad request - invalid workflow
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GithubWorkflowErrorResponse"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GithubWorkflowErrorResponse"

components:
  schemas:
    GithubWorkflowRequest:
      type: object
      required:
        - workflow_type
        - action
      properties:
        workflow_type:
          $ref: "#/components/schemas/GithubWorkflowType"
        action:
          $ref: "#/components/schemas/WorkflowActionType"
        parameters:
          $ref: "#/components/schemas/GithubWorkflowRequestParameters"
      additionalProperties: false

    GithubWorkflowResponse:
      type: object
      required:
        - workflow_type
        - workflow_id
      properties:
        workflow_type:
          $ref: "#/components/schemas/GithubWorkflowType"
        workflow_id:
          type: string
          description: ID of the workflow
        action:
          $ref: "#/components/schemas/WorkflowActionType"
      additionalProperties: false

    GithubWorkflowErrorResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: Message
          example: "Wrong workflow type"
      additionalProperties: false

    GithubWorkflowRequestParameters:
      type: object
      required:
        - repository
      properties:
        repository:
          type: string
          description: Repository name
      additionalProperties: false

    GithubWorkflowType:
      type: string
      description: Type of the workflow
      enum:
        - GenerateReportGithubWorkflow

    WorkflowActionType:
      type: string
      description: Action to be performed on the workflow
      enum:
        - start
        - stop

  securitySchemes:
    # Add security schemes here if authentication is implemented
    # apiKey:
    #   type: apiKey
    #   in: header
    #   name: X-API-Key

tags:
  - name: Workflows
    description: Operations related to workflow management
