version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - '6333:6333' # REST API
      - '6334:6334' # GRPC
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__SERVICE__HTTP_PORT=6333

volumes:
  qdrant_storage:
