version: '3.8'

services:

  pg-src:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    ports:
      - '54321:5432'
    volumes:
      - './.data/postgres/src:/var/lib/postgresql/data'

  pg-dst:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    ports:
      - '54322:5432'
    volumes:
      - './.data/postgres/dst:/var/lib/postgresql/data'

volumes:
  db:
    driver: local
