name: Lint and test
on:
  pull_request:

jobs:
  lint-test:
    name: Run linter, unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./devops/app

    steps:
      - uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0

      - name: Detect changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            be-supplier-portal:
              - 'cmd/**'
              - 'go.mod'

      - uses: actions/setup-go@v4
        with:
          go-version: "1.21.x"
          cache: false

      - name: Run lint
        uses: golangci/golangci-lint-action@v3.4.0
        with:
          version: v1.55.1
          args: -v --timeout=10m0s --config ./.golangci-lint.yml
          skip-cache: true
          working-directory: ./devops/app

      - name: Run tests
        run: |
          go test -short -mod=mod -v -p=1 -count=1 ./...